name: Database Migration

on:
  push:
    branches: [ main, 'feat/*', 'fix/*' ]
    paths:
      - 'backend/db/migration/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/db/migration/**'
  workflow_dispatch:

permissions:
  actions: read           # Potentially needed for private repositories
  id-token: write         # Required for OIDC authentication

jobs:
  # Deployment to development environment
  migrate-dev:
    name: 'Migrate Database - Development Environment'
    uses: ./.github/workflows/database-deploy.yml
    with:
      environment: 'Development'
      environment_name: 'development'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Deployment to production environment (requires manual approval)
  migrate-prod:
    name: 'Migrate Database - Production Environment'
    needs: migrate-dev # Requires the development migration to complete first
    # Environment protection rules handle approvals
    uses: ./.github/workflows/database-deploy.yml
    with:
      environment: 'Production'
      environment_name: 'production'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}